[build]
  command = "npm install --legacy-peer-deps && npm run build:netlify"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200